# docker-compose.yml
version: "3.7"

networks:
  docker.network:
    driver: bridge

volumes:
  mysql_data:

services:
  php:
    build: ./app/docker/php
    restart: unless-stopped
    container_name: docker.php
    tty: true
    depends_on:
      - mysql
    networks:
      - docker.network
    volumes:
      - .:/var/www

  apache:
    build: ./app/docker/apache
    restart: unless-stopped
    container_name: docker.apache
    tty: true
    depends_on:
      - php
    ports:
      - "80:80"
      - "443:443"
    networks:
      - docker.network
    volumes:
      - .:/var/www
<<<<<<< Updated upstream
      #- ./docker/apache/ssl_certs_app:/etc/apache2/ssl_certs_app:ro
      #- ${SSL_CERTS_PATH}:/etc/letsencrypt/live/app.ucredcredito.com/:ro
      - /etc/letsencrypt/live/app.ucredcredito.com/:/etc/letsencrypt/live/app.ucredcredito.com/:ro
=======
      # O volume dos certificados será definido nos arquivos de override
      # para o ambiente específico.
      # Para o ambiente de desenvolvimento, o Dockerfile já prepara um diretório
      # /etc/apache2/ssl_certs_app, e os certificados de desenvolvimento serão copiados
      # para lá durante a build ou via volume, dependendo de como você preferir.
      # Para produção, montaremos o Let's Encrypt diretamente.
>>>>>>> Stashed changes

  mysql:
    image: mysql:5.7
    restart: unless-stopped
    container_name: docker.mysql
    tty: true
    mem_limit: 1g
    deploy:
      resources:
        limits:
          memory: 1g
        reservations:
          memory: 512m
    networks:
      - docker.network
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-development}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-mysql}
      MYSQL_USER: ${MYSQL_USER:-mysql}

  phpmyadmin:
    image: phpmyadmin
    container_name: docker.phpmyadmin
    tty: true
    depends_on:
      - mysql
    ports:
      - "8080:80"
    networks:
      - docker.network
    environment:
      PMA_HOST: mysql
      PMA_ARBITRARY: 1
      PMA_PORT: 3306
