# docker-compose.prod.yml
version: "3.7"

services:
  apache:
    volumes:
      # Mapeia os arquivos de certificado diretamente
      - ${SSL_CERTS_PATH_PROD}/fullchain.pem:/etc/apache2/ssl_certs_app/fullchain.pem:ro
      - ${SSL_CERTS_PATH_PROD}/privkey.pem:/etc/apache2/ssl_certs_app/privkey.pem:ro
